# THIS MAY SEEM CONFUSING, REFERENCE THE HELP SECTION OR ASK THE DEVELOPER HIMSELF
# BTHIEF - A CUSTOM THEFT PLUGIN MADE BY BROSWEN
#                         
use-economy: true
theft-reward: 1000
move-drugs: false
use-thief-delay: true
thief-delay: 30
use-thiefstick-delay: true
thiefstick-delay: 240
jail-location:
  world: world
  x: 1
  y: 70
  z: 3
use-jail-plugin: false
jail-name: jail
jail-time: 60